version: '3'
services:
  ldap:
    hostname: ldap
    container_name: ldap
    image: mikerthomsen/apacheds-docker-for-nifi
    ports:
      - "389:10389"
    volumes:
      - /opt/odp/ldap:/opt/odp/ldap:ro
  elasticsearch:
    hostname: elasticsearch
    container_name: elasticsearch
    image: "elasticsearch:latest"
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    container_name: kibana
    image: "kibana:latest"
    ports:
      - "5601:5601"
    depends_on: 
      - elasticsearch
    links:
      - elasticsearch
    environment:
      - elasticsearch.url=http://elasticsearch:9200
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /opt/nifi_demo/mongo-data:/data
      - /opt/nifi_demo/mongo:/opt/nifi_demo
  nifi:
    hostname: demo.nifi
    image: secured-nifi
    container_name: nifi
    environment:
      - AUTH=ldap
      - KEYSTORE_PATH=/opt/demo.nifi/keystore.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=U8khkCbNJKMyXFGyftAhv0Fg/qQrTsXH8VYQpglz1uo
      - TRUSTSTORE_PATH=/opt/demo.nifi/truststore.jks
      - TRUSTSTORE_PASSWORD=sh4TaEf9uqMMkq+A5XPIWraNPQVPv9HMdsHMmkD2iLw
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=CN=initialAdmin, OU=NiFi
      - LDAP_AUTHENTICATION_STRATEGY=SIMPLE
      - LDAP_MANAGER_DN=uid=admin,ou=system
      - LDAP_MANAGER_PASSWORD=secret
      - LDAP_USER_SEARCH_BASE=ou=people,dc=nifi,dc=com
      - LDAP_USER_SEARCH_FILTER=uid={0}
      - LDAP_IDENTITY_STRATEGY=USE_USERNAME
      - LDAP_URL=ldap://ldap:10389
      - NIFI_WEB_HTTP_HOST=demo.nifi
      - NIFI_WEB_HTTP_PORT=8888
    ports:
      - 8080:8080
      - 443:8443
    links:
      - ldap
      - elasticsearch
      - mongo
      - nifi2
    volumes:
      - /tmp/nifi:/opt/nifi_in
      - ./security_output/demo.nifi:/opt/demo.nifi
  nifi2:
    hostname: nifi2
    container_name: nifi2
    image: "apache/nifi:latest"
    environment:
      - NIFI_WEB_HTTP_HOST=nifi2
      - NIFI_WEB_HTTP_PORT=9999
      - NIFI_REMOTE_INPUT_HOST=nifi2
    ports:
      - 9999:9999