version: '3'
services:
  elasticsearch:
    hostname: elasticsearch
    container_name: elasticsearch
    image: "elasticsearch:latest"
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    container_name: kibana
    image: "kibana:latest"
    ports:
      - "5601:5601"
    depends_on: 
      - elasticsearch
    links:
      - elasticsearch
    environment:
      - elasticsearch.url=http://elasticsearch:9200
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /opt/nifi_demo/mongo-data:/data
      - /opt/nifi_demo/mongo:/opt/nifi_demo
  nifi:
    hostname: nifi
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - 8080:8080
    links:
      - elasticsearch
      - mongo
      - nifi2
    volumes:
      - /tmp/nifi:/opt/nifi_in
  nifi2:
    hostname: nifi2
    container_name: nifi2
    image: "apache/nifi:latest"
    environment:
      - NIFI_WEB_HTTP_HOST=nifi2
      - NIFI_WEB_HTTP_PORT=9999
      - NIFI_REMOTE_INPUT_HOST=nifi2
    ports:
      - 9999:9999