version: "3"
services:
  mongocfg:
    container_name: mongocfg
    hostname: mongocfg
    image: mongo:latest
    command: mongod --configsvr --replSet myrs --dbpath /tmp --bind_ip_all --sslMode requireSSL --sslPEMKeyFile /opt/mongo/mongocfg/combined.pem --sslCAFile /opt/mongo/nifi-cert.pem
    volumes:
      - ./nifi_mongo:/opt/mongo:ro
  mongo1:
    container_name: mongo1
    hostname: mongo1
    image: mongo:latest
    command: mongod --shardsvr --replSet myrs_int  --dbpath /tmp --bind_ip_all --sslMode requireSSL --sslPEMKeyFile /opt/mongo/mongo1/combined.pem --sslCAFile /opt/mongo/nifi-cert.pem
    links:
      - mongo2
    volumes:
      - ./nifi_mongo:/opt/mongo:ro
  mongo2:
    container_name: mongo2
    hostname: mongo2
    image: mongo:latest
    command: mongod --shardsvr --replSet myrs_int  --dbpath /tmp --bind_ip_all --sslMode requireSSL --sslPEMKeyFile /opt/mongo/mongo2/combined.pem --sslCAFile /opt/mongo/nifi-cert.pem
    volumes:
      - ./nifi_mongo:/opt/mongo:ro
  mongos:
    container_name: mongos
    hostname: mongos
    image: mongo:latest
    command: mongos --configdb myrs/mongocfg:27019 --bind_ip_all --sslMode requireSSL --sslPEMKeyFile /opt/mongo/mongos/combined.pem --sslCAFile /opt/mongo/nifi-cert.pem
    volumes:
      - ./nifi_mongo:/opt/mongo:ro
    links:
      - mongocfg
  registry.nifi:
    container_name: registry
    hostname: registry.nifi
    image: apache/nifi-registry:0.2.0
    ports: 
      - 18080:18080
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
  nifi:
    container_name: nifi
    image: apache/nifi:1.7.1
    hostname: demo.nifi
    ports:
      - 8080:8080
    links:
      - mongo1
      - mongo2
      - mongos
      - mongocfg
    volumes:
      - ./nifi_mongo:/opt/mongo:ro
  nifi_s2s:
    container_name: nifi_s2s
    image: apache/nifi:1.7.1
    hostname: s3s.nifi
    ports: 
      - 9999:8080
    links:
      - nifi
