version: "3.1"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
  nifi:
    hostname: nifi
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - 8080:8080
    links:
      - postgres
      - nifi2
    volumes:
      - /tmp/nifi:/opt/nifi_in
  nifi2:
    hostname: nifi2
    container_name: nifi2
    image: "apache/nifi:latest"
    environment:
      - NIFI_WEB_HTTP_HOST=nifi2
      - NIFI_WEB_HTTP_PORT=9999
      - NIFI_REMOTE_INPUT_HOST=nifi2
    ports:
      - 9999:9999
